const growthData = [
  {
    ppmc: "绿色草原散养羊",
    cdxx: "内蒙古阿巴嘎旗",
    yl: "1个月",
    gypjtz: "12.5kg",
    mypjtz: "10.5kg",
    fyxm: "口蹄疫",
    fyyp: "鼠尾草",
    qcypm: "某药品",
    qcsj: "2021-10-14",
    yyypm: "某药品",
    yysj: "2021-10-14"
  },
  {
    ppmc: "绿色草原散养羊",
    cdxx: "内蒙古阿巴嘎旗",
    yl: "2个月",
    gypjtz: "12.5kg",
    mypjtz: "10.5kg",
    fyxm: "口蹄疫",
    fyyp: "鼠尾草",
    qcypm: "某药品",
    qcsj: "2021-10-14",
    yyypm: "某药品",
    yysj: "2021-10-14"
  },
  {
    ppmc: "绿色草原散养羊",
    cdxx: "内蒙古阿巴嘎旗",
    yl: "3个月",
    gypjtz: "12.5kg",
    mypjtz: "10.5kg",
    fyxm: "口蹄疫",
    fyyp: "鼠尾草",
    qcypm: "某药品",
    qcsj: "2021-10-14",
    yyypm: "某药品",
    yysj: "2021-10-14"
  },
  {
    ppmc: "绿色草原散养羊",
    cdxx: "内蒙古阿巴嘎旗",
    yl: "4个月",
    gypjtz: "12.5kg",
    mypjtz: "10.5kg",
    fyxm: "口蹄疫",
    fyyp: "鼠尾草",
    qcypm: "某药品",
    qcsj: "2021-10-14",
    yyypm: "某药品",
    yysj: "2021-10-14"
  },
  {
    ppmc: "绿色草原散养羊",
    cdxx: "内蒙古阿巴嘎旗",
    yl: "5个月",
    gypjtz: "12.5kg",
    mypjtz: "10.5kg",
    fyxm: "口蹄疫",
    fyyp: "鼠尾草",
    qcypm: "某药品",
    qcsj: "2021-10-14",
    yyypm: "某药品",
    yysj: "2021-10-14"
  },
  {
    ppmc: "绿色草原散养羊",
    cdxx: "内蒙古阿巴嘎旗",
    yl: "6个月",
    gypjtz: "12.5kg",
    mypjtz: "10.5kg",
    fyxm: "口蹄疫",
    fyyp: "鼠尾草",
    qcypm: "某药品",
    qcsj: "2021-10-14",
    yyypm: "某药品",
    yysj: "2021-10-14"
  },
  {
    ppmc: "绿色草原散养羊",
    cdxx: "内蒙古阿巴嘎旗",
    yl: "7个月",
    gypjtz: "12.5kg",
    mypjtz: "10.5kg",
    fyxm: "口蹄疫",
    fyyp: "鼠尾草",
    qcypm: "某药品",
    qcsj: "2021-10-14",
    yyypm: "某药品",
    yysj: "2021-10-14"
  },
  {
    ppmc: "绿色草原散养羊",
    cdxx: "内蒙古阿巴嘎旗",
    yl: "8个月",
    gypjtz: "12.5kg",
    mypjtz: "10.5kg",
    fyxm: "口蹄疫",
    fyyp: "鼠尾草",
    qcypm: "某药品",
    qcsj: "2021-10-14",
    yyypm: "某药品",
    yysj: "2021-10-14"
  },
  {
    ppmc: "绿色草原散养羊",
    cdxx: "内蒙古阿巴嘎旗",
    yl: "9个月",
    gypjtz: "12.5kg",
    mypjtz: "10.5kg",
    fyxm: "口蹄疫",
    fyyp: "鼠尾草",
    qcypm: "某药品",
    qcsj: "2021-10-14",
    yyypm: "某药品",
    yysj: "2021-10-14"
  },
  {
    ppmc: "绿色草原散养羊",
    cdxx: "内蒙古阿巴嘎旗",
    yl: "10个月",
    gypjtz: "12.5kg",
    mypjtz: "10.5kg",
    fyxm: "口蹄疫",
    fyyp: "鼠尾草",
    qcypm: "某药品",
    qcsj: "2021-10-14",
    yyypm: "某药品",
    yysj: "2021-10-14"
  }
];
export default growthData;
